//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class КПEntities : DbContext
    {
        public КПEntities()
            : base("name=КПEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Арендатор> Арендатор { get; set; }
        public virtual DbSet<Арендодатель> Арендодатель { get; set; }
        public virtual DbSet<Договор> Договор { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Здания> Здания { get; set; }
        public virtual DbSet<ОбщиеПомещения> ОбщиеПомещения { get; set; }
        public virtual DbSet<ПоказанияСчётчика> ПоказанияСчётчика { get; set; }
        public virtual DbSet<Помещения> Помещения { get; set; }
        public virtual DbSet<ПослужнойСписок> ПослужнойСписок { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Электрооборудование> Электрооборудование { get; set; }
    }
}
