//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Должности
    {
        public Должности()
        {
            this.ПослужнойСписок = new HashSet<ПослужнойСписок>();
        }
    
        public int IDДолжности { get; set; }
        public string НаименованиеДолжности { get; set; }
        public Nullable<decimal> Оклад { get; set; }
        public string Требования { get; set; }
    
        public virtual ICollection<ПослужнойСписок> ПослужнойСписок { get; set; }
    }
}
