//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Здания
    {
        public Здания()
        {
            this.Арендодатель = new HashSet<Арендодатель>();
            this.Помещения = new HashSet<Помещения>();
            this.ОбщиеПомещения = new HashSet<ОбщиеПомещения>();
        }
    
        public string Наименование { get; set; }
        public Nullable<int> Этажность { get; set; }
        public string ПочтовыеДанные { get; set; }
        public Nullable<int> НомерПомещения { get; set; }
        public int IDЗдания { get; set; }
    
        public virtual ICollection<Арендодатель> Арендодатель { get; set; }
        public virtual ICollection<Помещения> Помещения { get; set; }
        public virtual ICollection<ОбщиеПомещения> ОбщиеПомещения { get; set; }
    }
}
