//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОбщиеПомещения
    {
        public string НаименованиеКоридоры { get; set; }
        public Nullable<int> Туалеты { get; set; }
        public Nullable<int> Этаж { get; set; }
        public Nullable<int> IDЗдания { get; set; }
        public int IDОбщПомещения { get; set; }
    
        public virtual Здания Здания { get; set; }
    }
}
