//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПослужнойСписок
    {
        public Nullable<System.DateTime> ДатаЗанятияДолжности { get; set; }
        public string КраткаяХарактеристика { get; set; }
        public int IDПослужногоСписка { get; set; }
        public Nullable<int> IDДолжности { get; set; }
        public Nullable<int> IDСотрудника { get; set; }
    
        public virtual Должности Должности { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
