//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПоказанияСчётчика
    {
        public Nullable<int> Номер { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Арендодатель { get; set; }
        public string Месяц { get; set; }
        public Nullable<int> Год { get; set; }
        public Nullable<int> Сумма { get; set; }
        public Nullable<int> IDЭлектрооборудование { get; set; }
        public int IDСчётчика { get; set; }
        public Nullable<int> IDСотрудника { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Электрооборудование Электрооборудование { get; set; }
    }
}
