//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public Сотрудники()
        {
            this.Арендодатель = new HashSet<Арендодатель>();
            this.ПоказанияСчётчика = new HashSet<ПоказанияСчётчика>();
            this.ПослужнойСписок = new HashSet<ПослужнойСписок>();
        }
    
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Фото { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public string Пол { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> Телефон { get; set; }
        public string Образование { get; set; }
        public int IDСотрудника { get; set; }
        public string ПаспортныеДанные { get; set; }
    
        public virtual ICollection<Арендодатель> Арендодатель { get; set; }
        public virtual ICollection<ПоказанияСчётчика> ПоказанияСчётчика { get; set; }
        public virtual ICollection<ПослужнойСписок> ПослужнойСписок { get; set; }
    }
}
